routing:
  domain: demo.cxcloud.com
  ssl: true
  rules:
    - path: /api/commerce
      serviceName: service-commerce
      servicePort: 4003
    - path: /api/content
      serviceName: service-content
      servicePort: 4003
    - path: /api/search
      serviceName: service-search
      servicePort: 4003
    - path: /
      serviceName: angular-demo
      servicePort: 80
